### ISSUE TITLE
Set offset on start

### ISSUE THREAD

**Issue by KyleAMathews** [alfred-landrum/node-kafka-native#31]
I'm writing a script where I'd like to read all messages on a topic from the beginning. Is there a way to set the offset at start to 0 in the consumer options? Right now I keep having to manually deleting the offset directory.

**Comment by pmidge** [comment]
@KyleAMathews AFAIK, no. I wanted to use a different method than the file, so I wrote a Redis-based offset manager. If tracking the offset isn't important to you, you can simply create an object with the same public methods as the built-in [OffsetDirectory](https://github.com/alfred-landrum/node-kafka-native/blob/master/lib/offsetdirectory.js) class and pass it into the consumer via `options.offset_manager`.

Then, when requested, you can supply whatever starting offset you like.

**Comment by KyleAMathews** [comment]
@pmidge ok I did see the option in some of the tests of creating your own way of managing offsets so that could work too. Let me look at this more. I might just create a PR to add the option to overwrite the existing offset in the offset-directory if @alfred-landrum likes that. Otherwise, I'll just create a custom OffsetDirectory class that always starts at 0.

**Comment by alfred-landrum** [comment]
@KyleAMathews @pmidge is correct: there's no direct way of doing this with the code as-is, and using a modified OffsetDirectory object is likely the easiest way forward.

FYI that while looking in this, I discovered a cleanup issue to address. It shouldn't affect your work, but fyi in case you want more detail about how the offsets are handled: #35

**Comment by KyleAMathews** [comment]
Actually just ended up creating a new random tmp directory on start. That proved simplest of all. Thanks @alfred-landrum and @pmidge!
